language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

stages:
  - test

matrix:
  fast_finish: true
  include:
    - stage: test
      php: 7.1
    - stage: test
      php: 7.2

install:
  - make install

script:
  - make test

after_success:
  - yarn run encore production
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add ./src/Resources/dist/
  - git commit -m'built js dist file'
  - git remote add origin-pages https://${GIT_ACCESS_TOKEN}@github.com:silasjoisten/sonata-multiupload-bundle.git > /dev/null 2>&1
  - git push --quiet --set-upstream origin ${TRAVIS_BRANCH}

notifications:
  email: silas.joisten@hotmail.de
